server: 
   port: 8083
   servlet: 
      context-path: /boot-redis 
logging: 
   path: /user/local/log
   level: 
      com.boot.redis.controller: DEBUG   
# DataSource Config
spring:
    datasource:
        driver-class-name: org.h2.Driver
        schema: classpath:db/ddl.sql
        data: classpath:db/data.sql
        url: jdbc:h2:tcp://localhost/~/test
        username: sa
        password: 
